const fs = require('fs');
const filePath = 'src/data/blog/posts.ts';
let content = fs.readFileSync(filePath, 'utf8');

// Find the first id: "14"
const id14Start1 = content.indexOf('  id: "14",');
if (id14Start1 !== -1) {
    // Find the second id: "14"
    const id14Start2 = content.indexOf('  id: "14",', id14Start1 + 1);
    
    if (id14Start2 !== -1) {
        // Find where the second object starts
        const braceStart = content.lastIndexOf('{', id14Start2);
        // Find where the second object ends (it should be the last object in the array)
        let braceEnd = content.indexOf(']', braceStart);
        // We want to delete from braceStart to the comma before it, or just up to the end of the array
        
        // Actually, we know that the first id: 14 is the correct one generated by fixTrainerCost.js.
        // Wait, let's check which one has the correctly rendered table!
        const obj1 = content.substring(id14Start1, id14Start2);
        const obj2 = content.substring(id14Start2, braceEnd);
        
        console.log("Obj1 length:", obj1.length);
        console.log("Obj1 contains <table>:", obj1.includes('<table'));
        console.log("Obj2 length:", obj2.length);
        console.log("Obj2 contains <table>:", obj2.includes('<table'));
        
        if (obj1.includes('<table') && !obj2.includes('<table')) {
            // Delete obj2
            const commaBefore = content.lastIndexOf(',', braceStart);
            content = content.substring(0, commaBefore) + content.substring(braceEnd - 1); // keep the \n]
            fs.writeFileSync(filePath, content);
            console.log("Deleted the second (duplicate/broken) ID 14.");
        } else if (obj2.includes('<table') && !obj1.includes('<table')) {
            // Delete obj1
            const braceStart1 = content.lastIndexOf('{', id14Start1);
            const commaBefore1 = content.lastIndexOf(',', braceStart1);
            content = content.substring(0, commaBefore1) + content.substring(braceStart - 1);
            fs.writeFileSync(filePath, content);
            console.log("Deleted the first (duplicate/broken) ID 14.");
        } else {
             // Just delete the second one
             const commaBefore = content.lastIndexOf(',', braceStart);
             content = content.substring(0, commaBefore) + '\n' + content.substring(braceEnd);
             fs.writeFileSync(filePath, content);
             console.log("Deleted second ID 14 fallback.");
        }
    } else {
        console.log("Only one ID 14 found.");
    }
}
